faderim:
    front-controller: Seguradora\Controller\AdminFrontController
doctrine:
  source-folders:
     - src/Faderim     
     - src/Seguradora  
  proxy-dir: false
  auto-genarate-proxy: true
  charset: utf8
  driverOptions:
    1002: SET NAMES utf8